--- # This is the master playbook for appservers
- hosts: appservers
  remote_user: vagrant
  become: yes
  become_method: sudo
  connection: ssh
  pre_tasks: 
  - name: when did the role start to run
    raw: date > /home/vagrant/startofrole.log
  roles: 
    - appservers
  post_tasks:
  - name: when did the role stop running
    raw: date > /home/vagrant/stopofrole.log
