# Iptables variables
incoming:
  - name: SSH
    port: 22
  - name: HTTP
    port: 80
  - name: HTTPS
    port: 443

# php5 configuration
php_memory_limit: "128M"
php_max_execution_time: "10"
php_upload_max_filesize: "10M"
php_apc_enabled_in_ini: false
php_opcache_enabled_in_ini: true
php_expose_php: "Off"
php_short_open_tag: true
php_enable_php_fpm: true
php_enable_webserver: false
php_conf_path: "/etc/php5/fpm"
php_packages:
  - php5
  - php5-cli
  - php-pear
  - php5-common
  - php5-curl
  - php5-dev
  - php5-gd
  - php5-gmp
  - php5-mcrypt
  - php5-mysql
  - php5-xmlrpc
  - php5-xsl
  - php5-fpm

backup_files: True
