---
## common tasks
- include: 01-hosts_file.yml

## database tasks
- include: 02-create_databases.yml
  when: "server_role|d('') == 'db'"

## application tasks
- include: 03-app_dir.yml
  when: "server_role|d('') == 'app'"
- include: 04-install_wp.yml
  when: "server_role|d('') == 'app'"
- include: 05-nginx_vhost.yml
  when: "server_role|d('') == 'app'"

## load balancers tasks
- include: 06-add_haproxy.yml
  when: "server_role|d('') == 'lb'"
