---
# playbook to add a user to remote systems
- hosts: all
  remote_user: vagrant
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no
  tasks: 
  - name: create a cicd group
    group: name=cicd state=present
  - name: create a user named 'ansible' 
    user: name=ansible comment="Ansible User" shell=/bin/bash group=cicd
