---
# playbook to remove more than one user to remote systems
- hosts: all
  remote_user: vagrant
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no
  tasks: 
  - name: remove users from a list 
    user: name={{ item }} state=absent remove=true
    with_items: 
       - jenkins
       - rundeck
       - puppet
