---

- name: Install rkhunter
  apt: name=rkhunter state=installed update_cache=yes install_recommends=no

- name: Add rkhunter configuration file
  template: src=rkhunter.conf.j2 dest=/etc/rkhunter.conf owner=root group=root
  notify: update rkhunter
