---
galaxy_info:
  author: slash4
  description: Install a high available, scalable wordpress cluster. Beta Test!
  company: slash4
  license: MIT
  min_ansible_version: 1.9
  platforms:
  - name: Ubuntu
    versions:
    - all
  categories:
  - web
