---
#Provision Droplets
#- include: droplets.yml

# Common tasks
- hosts: wordpress_roles
  gather_facts: True
  become: yes
  become_method: sudo
  roles:
    - { role: common, tags: ["common"] }
    - { role: openssh, tags: ["openssh"] }
    - { role: fail2ban, tags: ["fail2ban"] }
    - { role: rkhunter, tags: ["rkhunter"] }
#    - { role: iptables, tags: ["iptables"] }

# Load Balancer(s) roles
- hosts: wordpress_lb_roles
  become: yes
  become_method: sudo
  roles:
    - { role: haproxy, tags: ["haproxy"] }

# Application Server(s) roles
- hosts: wordpress_app_roles
  become: yes
  become_method: sudo
  roles:
    - { role: nginx, tags: ["nginx"] }
    - { role: php5, tags: ["php5"] }
    - { role: hhvm, tags: ["hhvm"] }

# Database Server(s) roles
- hosts: wordpress_db_roles
  become: yes
  become_method: sudo
  vars_files:
      - group_vars/passwords.yml
  roles:
    - { role: mysql, tags: ["mysql"] }

# Installing the application on servers
- hosts: wordpress_roles
  become: yes
  become_method: sudo
  vars_files:
      - group_vars/passwords.yml
  handlers:
      - include: roles/hhvm/handlers/main.yml
      - include: roles/nginx/handlers/main.yml
      - include: roles/mysql/handlers/main.yml
      - include: roles/haproxy/handlers/main.yml
  roles:
    - { role: application, tags: ["application"] }
    - { role: backup, tags: ["backup"] }
