--- 
# This is a basic playbook header
- hosts: all
  remote_user: vagrant
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no
  tasks: 
  - name: Get uptime of servers
    shell: "uptime"
    register: uptime
  - debug: var=uptime
