---

openssh_client:
    Port: "22"
    Host: "*"
    ForwardAgent: "no"
    ForwardX11: "no"
    ForwardX11Trusted: "yes"
    RhostsRSAAuthentication: "no"
    RSAAuthentication: "yes"
    PasswordAuthentication: "yes"
    HostbasedAuthentication: "no"
    GSSAPIAuthentication: "no"
    GSSAPIDelegateCredentials: "no"
    GSSAPIKeyExchange: "no"
    GSSAPITrustDNS: "no"
    BatchMode: "no"
    CheckHostIP: "yes"
    AddressFamily: "any"
    ConnectTimeout: "0"
    StrictHostKeyChecking: "ask"
    IdentityFile: "~/.ssh/identity"
    IdentityFile: "~/.ssh/id_rsa"
    IdentityFile: "~/.ssh/id_dsa"
    Protocol: "2,1"
    Cipher: "3des"
    Ciphers: "aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-cbc,3des-cbc"
    MACs: "hmac-md5,hmac-sha1,umac-64@openssh.com,hmac-ripemd160"
    EscapeChar: "~ Tunnel no"
    TunnelDevice: "any:any"
    PermitLocalCommand: "no"
    VisualHostKey: "no"
    ProxyCommand: "ssh -q -W %h:%p gateway.example.com"
    RekeyLimit: "1G 1h"
    SendEnv: "LANG LC_*"
    HashKnownHosts: "yes"
    GSSAPIAuthentication: "yes"
    GSSAPIDelegateCredentials: "no"
    Compression: "no"
    CompressionLevel: "4"

openssh_server:
    Port: "22"
    AddressFamily: "any"
    Protocol: "2"
    UsePrivilegeSeparation: "yes"
    KeyRegenerationInterval: "3600"
    ServerKeyBits: "1024"
    SyslogFacility: "AUTH"
    LogLevel: "INFO"
    LoginGraceTime: "120"
    PermitRootLogin: "no"
    StrictModes: "yes"
    MaxAuthTries: "6"
    MaxSessions: "10"
    RSAAuthentication: "yes"
    PubkeyAuthentication: "yes"
    AuthorizedKeysFile: "%h/.ssh/authorized_keys"
    IgnoreRhosts: "yes"
    RhostsRSAAuthentication: "no"
    HostbasedAuthentication: "no"
    IgnoreUserKnownHosts: "no"
    PermitEmptyPasswords: "no"
    ChallengeResponseAuthentication: "no"
    PasswordAuthentication: "no"
    KerberosAuthentication: "no"
    KerberosGetAFSToken: "no"
    KerberosOrLocalPasswd: "yes"
    KerberosTicketCleanup: "yes"
    GSSAPIAuthentication: "no"
    GSSAPICleanupCredentials: "yes"
    X11Forwarding: "yes"
    X11DisplayOffset: "10"
    X11UseLocalhost: "yes"
    PrintMotd: "no"
    PrintLastLog: "yes"
    TCPKeepAlive: "yes"
    UseLogin: "no"
    MaxStartups: "10:30:100"
    Banner: "none"
    AcceptEnv: "LANG LC_*"
    Subsystem: "sftp /usr/lib/openssh/sftp-server"
    UsePAM: "yes"
    UseDNS: "no"
    AllowAgentForwarding: "yes"
    AllowTcpForwarding: "yes"
    GatewayPorts: "no"
    ClientAliveInterval: "1750"
    ClientAliveCountMax: "0"
    PermitUserEnvironment: "no"
    Compression: "delayed"
    PidFile: "/var/run/sshd.pid"
    PermitTunnel: "no"
    ChrootDirectory: "none"
    HostKey: "/etc/ssh/ssh_host_ed25519_key"
    HostKey: "/etc/ssh/ssh_host_rsa_key"
