--- # Start AT Playbook example
- hosts: appservers
  remote_user: vagrant
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no

  tasks: 
  - name: Install telnet
    yum: pkg=telnet state=latest
  - name: Install Lynx
    yum: pkg=lynx state=latest
  - name: List Home
    command: ls -al /home/vagrant
    register: result
  - debug: var=result

