--- # This is my first YAML playbook for Ansible
- hosts: centos
  remote_user: vagrant
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no
  vars:
    playbook_version: 0.1b
  vars_files:
    - conf/copyright.yml
    - conf/webdefaults.yml
  vars_prompt:
    - name: pkg_name
      prompt: Install Which Package?
  tasks:
    - name: Install {{ pkg_name }}
      action: yum name={{ pkg_name }} state=installed
