--- # Demonstration of SELinux
    # http://docs.ansible.com/ansible/selinux_module.html
    # http://docs.ansible.com/ansible/playbooks_prompts.html
- hosts: appservers
  remote_user: vagrant
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no
  vars_prompt:
    - name: selinux_state
      prompt: Which SELinux state enforcing, permissive, or disabled?
      private: no
  tasks: 
   - name: Changing SELinux Configuration to {{ selinux_state }} 
     selinux: policy=targeted state={{ selinux_state }}

