--- # A module that runs the script modules
    # link: http://docs.ansible.com/ansible/script_module.html
- hosts: appservers
  remote_user: vagrant
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no
  tasks: 
  - script: /home/vagrant/playbooks/system_uptime.sh creates=/home/vagrant/playbooks/system_uptime.log
  
  
