--- # playbook demonstrating the stat module
    # link: http://docs.ansible.com/ansible/stat_module.html
- hosts: appservers
  remote_user: vagrant
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no
  tasks: 
  - name: Does file/directory in a path exist or not? 
    stat: path=/home/vagrant/abc
    register: p
  - debug: msg="Path Exists and is a Directory"
    when: p.stat.isdir is defined and p.stat.isdir
