---
- hosts: all
  gather_facts: no
  remote_user: vagrant
  connection: ssh
  tasks:

  - name: install ssh key
    authorized_key: user=vagrant
                    key="{{lookup('file', '/home/vagrant/.ssh/id_rsa.pub') }}"
                    state=present
