#- name: Create the user(s)
#  user: name={{ item.name }} shell=/bin/bash state=present
#  with_items: common_users

#- name: Add user ssh keys
#  authorized_key: user={{ item.name }} key="{{ item.key }}"
#  with_items: common_users

#- name: Add user to sudoers
#  lineinfile: "dest=/etc/sudoers state=present line='{{ item.name }} ALL=(ALL) NOPASSWD: ALL'"
#  with_items: common_users
