--- # This is my second playbook
- hosts: appservers
  remote_user: vagrant
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no

  vars:
   playbook_version: 1.0b
  vars_files:
   - conf/copyright.yml
   - conf/webdefaults.yml
