# Define the Vagrant environment for Ansible 101
#
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Create some dev servers
  (1..1).each do |i|
    config.vm.define "web0#{i}" do |dev|
        dev.vm.box="ubuntu/wily64"
        dev.vm.hostname = "web0#{i}"
        dev.vm.network :private_network, ip: "192.168.34.1#{i}"
        dev.vm.provider "virtualbox" do |vb|
         vb.memory = "256"
        end
    end
  end

  # Create some dev servers
  (1..1).each do |i|
    config.vm.define "app0#{i}" do |dev|
        dev.vm.box="centos/7"
        dev.vm.hostname = "app0#{i}"
        dev.vm.network :private_network, ip: "192.168.34.2#{i}"
        dev.vm.provider "virtualbox" do |vb|
         vb.memory = "256"
        end
    end
  end

  # Create the Ansible Control Server
  config.vm.define :acs do |acs|
    acs.vm.box = "ubuntu/trusty64"
    acs.vm.hostname = "acs"
    acs.vm.network :private_network, ip: "192.168.34.10"
    acs.vm.provider "virtualbox" do |vb|
      vb.memory = "256"
    end
  end

end
