--- # Apache2 module playbook
- hosts: webservers
  remote_user: vagrant
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no

  tasks:
    - name: Disable the alias module in Apache2
      apache2_module: state=absent name=alias
