--- # Cron module example
- hosts: appservers
  remote_user: vagrant
  connection: ssh
  gather_facts: no
  tasks:
    - name: add a cron job to the test user
      cron: name="list files" state=absent

