--- # Delegate to function demo
- hosts: appservers
  remote_user: vagrant
  become: yes
  become_method: sudo
  connection: ssh

  tasks:
    - name: Run a remote ping on the app1
      raw: ping -c 4 app1 > /home/vagrant/Playbooks/pingapp1.out
      delegate_to: 127.0.0.1
    - name: Install a package 
      yum: pkg=lynx state=latest
    - name: Run a remote command on app2 to app1
      raw: ping -c 4 app2 > /home/vagrant/Playbooks/pingapp2.out
      delegate_to: 127.0.0.1
