--- # error handling example
- hosts: appservers
  user: vagrant
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no
  tasks:
    - name: Execute a command that will fail
      command: /bin/false
      ignore_errors: yes
    - name: Install telnet
      yum: pkg=telnet state=latest

