--- # the fetch module
- hosts: all
  remote_user: vagrant
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes

  tasks:
    - name: fetch a file from a remote server
      fetch: src=/etc/hosts dest=/home/vagrant/prefix-{{ ansible_hostname }} flat=yes

