--- # Loop playbook
- hosts: appservers
  remote_user: vagrant
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no
  
  # Start tasks
  tasks:
   - name: Add a list of users
     user: name={{ item }} state=present
     with_items:
       - user1
       - user2
       - user3

