--- # Remove Apache2 WebServer from everything
- hosts: all
  remote_user: vagrant
  become: yes
  become_method: sudo
  connection: ssh


  tasks:
    - name: Remove Apache2 from Ubuntu Servers
      apt: name=apache2 state=absent
      when: ansible_os_family == "Debian"

    - name: Remove HTTPD from CentOS Servers
      yum: name=httpd state=absent
      when: ansible_os_family == "RedHat"

