--- # Until playbook
- hosts: appservers
  remote_user: vagrant
  become: yes
  become_method: sudo
  connection: ssh
  
  tasks:
    - name: Install Apache2
      apt: pkg=apache2 state=latest
      when: ansible_os_family == "Debian"

    - name: Install Httpd
      yum: pkg=httpd state=latest
      when: ansible_os_family == "RedHat" 

    - name: verify status Apache2
      shell: service apache2 status
      when: ansible_os_family == "Debian"
      register: result
      until: result.stdout.find("apache2 is running") != -1
      retries: 5
      delay: 5
    - debug: var=result

    - name: verify status httpd
      shell: systemctl status httpd
      when: ansible_os_family == "RedHat"
      register: result
      until: result.stdout.find("active (running)") != -1
      retries: 5
      delay: 5
    - debug: var=result
