- name: Install Apache Webserver
  yum: pkg={{ redhat_apache }} state=latest update_cache=yes
  when: "ansible_os_family == 'RedHat'"
  notify: Restart HTTPD
  ignore_errors: yes

- name: Install Apache2 Weberver
  apt: pkg={{ debian_apache }} state=latest update_cache=yes
  when: "ansible_os_family == 'Debian'"
  ignore_errors: yes
